spring:
  application:
    name: myfirstwebapp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  level:
    com:
      wchamara:
        myfirstwebapp: debug
    org:
      springframework:
        web: info
