spring:
  application:
    name: learn-spring-boot

logging:
  level:
    org:
      springframework: info

currency-service:
  url: http://prod.currency-service.com
  username: produser
  password: prodpassword